### ISSUE TITLE
Create a Docker script to clean up / format Solidity

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#10]
We want to extend our beloved linter also to work with Solidity

Maybe we can become with a simple script to lint / format, before adding this to the main flow

Some promising links:
- https://blog.finxter.com/best-solidity-linter/
- https://github.com/prettier-solidity/prettier-plugin-solidity
- https://medium.com/coinmonks/introduction-to-solidity-linting-and-formatting-e838c074791a

Step 1:
- For beautifying Solidity code I would use `prettier` (I've used for several other text and works nicely)
- Install on your machine or in Docker and experiment a bit with some Solidity code on the web

Step 2:
- For linting https://github.com/duaraghav8/Ethlint seems the best
- Install on your machine or in Docker and experiment a bit with some Solidity code on the web

Step 3:
- Use the approach in https://github.com/sorrentum/sorrentum/blob/master/dev_scripts/ctags.sh to create a `dev_scripts/lint_solidity.sh`

**Comment by gpsaggese** [comment]
Assigned to @Jingyun-li

**Comment by gpsaggese** [comment]
@tamriq can you re-route to one of the team members?

**Comment by samarth9008** [comment]
@gpsaggese @tamriq 

I understand the overall goal for this issue that we are building a linter for solidity but I have few questions.

1) From my understanding, I will have to create a script which will run `prettier` and `ethlint` and from the reference of the `ctags.sh` it should run inside a docker container. Am I right about this? 

2) Are there any reference for setting up our python linter? I hope I will get some more clear idea from that too.

3) What will the end file looks like and how should I test it?

**Comment by gpsaggese** [comment]
Switched to @samarth9008 

> @gpsaggese @tamriq
> 
> I understand the overall goal for this issue that we are building a linter for solidity but I have few questions.
> 
> 1. From my understanding, I will have to create a script which will run `prettier` and `ethlint` and from the reference of the `ctags.sh` it should run inside a docker container. Am I right about this?

You need to write a script exactly like `ctags.sh` called `dev_scripts/lint_solidity.sh` but changing the container and the script to run.
`dev_scripts/lint_solidity.sh`
- creates a Docker container on the fly with the tools we need to lint (e.g., `prettier` and `ethlint`).
- creates a script `run_lint_solitidity.sh` invoking `prettier` and `ethlint`
- run the script inside Docker container to apply the linters to the files passed to the command line with `"$@"`

> 2. Are there any reference for setting up our python linter? I hope I will get some more clear idea from that too.

There is a bug about sharing our Python linter (https://github.com/cryptokaizen/cmamp/issues/4192), but that's a complicated system 

> 3. What will the end file looks like and how should I test it?

`dev_scripts/lint_solidity.sh` has the same structure as `ctags.sh`
Once that script runs the files passed to the script are transformed in place (e.g., they are going to be beautified and then issues are going to be found).

No need to test this transformation.

Let's start iterating (quickly and baby steps) and things are going to be clearer.

**Comment by samarth9008** [comment]
@gpsaggese 

Okay understood the concept. I am able to run the script for single files. However, for multiple files input from command lines, I am looping through the arguments but facing an error in that saying that `loop variable(arg): unbound variable`. I am working on it now. All code is pushed over here.

https://github.com/sorrentum/sorrentum/blob/Issue10_Create_a_Docker_script_to_clean_up/format_Solidity/dev_scripts/lint_solidity.sh

**Comment by samarth9008** [comment]
@gpsaggese 

What I have realised from this error is, since we are creating another script `/run_linter.sh` inside the main `lint_solidity.sh` which will run the linter on the files passed as a command line arguments inside the container. When we run the file `lint_solidity.sh`, first it will build a docker image and the environment variables. Then it will create a script file `run_linter.sh`. While creating that script, its loop variable `arg` which will read the command line arguments, will require a value. Since these values will be passed once we run the script inside the container and when it executes the `run_linter.sh` and not during the execution of `lint_solidity.sh`. So the execution will stop and it will not move forward. Also assigning the default value to `arg` variable will override the `arg` variable inside the for loop and the loop will not execute with the right files. 

I hope you have understood the error.

We can also try inputting the whole command line argument (The strings of files) as input to the `prettier` and `solium`. It works perfectly fine with the `prettier` but `solium` does not support multiple files input.

One solution I have found is instead of supplying each files on the command line, Can we supply the directory on the command line which contains our `*.sol` files? Directory support is provided for both of them.

Code: https://github.com/sorrentum/sorrentum/blob/Issue10_Create_a_Docker_script_to_clean_up/format_Solidity/dev_scripts/lint_solidity.sh

**Comment by samarth9008** [comment]
Found a better solution which will satisfy the requirements for passing the file names on command line

1) Created a temporary directory which will copy all the file names passed as command args.

2) Since prettier will accept multi-file inputs, we will pass `$@` to it and changes will happen at the permanent location.

3) The ethlint will lint the code on temporary directory and will present any errors on the terminal.

4) The temporary directory will then be deleted and any error which were displayed by the ethlint can be solved on the permanent location.

Created a PR of this.
