### ISSUE TITLE
Team1: Implement sandbox for Google Trends

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#13]

**Comment by gpsaggese** [comment]
Team1, we can't merge your PR https://github.com/sorrentum/sorrentum/pull/83/files since it's busted

<img width="736" alt="image" src="https://user-images.githubusercontent.com/33238329/228570058-c71c6315-e549-4fe3-b3f0-f2f9394c52f8.png">

My suggestion is:
1) create a new PR `Issue13_Team1_Implement_sandbox_for_Google_Trends_2` from master
2) copy *only* the new files in your dir under the project `sorrentum_sandbox/examples/ml_projects/SorrIssue14_Team1_Implement_sandbox_for_Google_Trends`
3) close the old PR

@samarth9008 can you pls help Team1 if needed?

**Comment by samarth9008** [comment]
Sure. Let us know if you face any issues.

**Comment by piyush-raj-pandey** [comment]
Professor,Samarth, if it's okay with you, we'd like to do this with you in
class tomorrow.

**Comment by samarth9008** [comment]
Sounds good.

**Comment by samarth9008** [comment]
Since tomorrow's class is online it would be better if you can implement the solution today itself. The issue which we are facing is, we are not able to generate a pull request from your branch because you have made changes to a lot files which was not required. Here is a detailed solutions of what we want you to do so generating future pull requests will be easy for us.

1) Create a new branch "Issue13_Team1_Implement_sandbox_for_Google_Trends_2" from master

2) Switch to the new branch locally. 
    "git switch Issue13_Team1_Implement_sandbox_for_Google_Trends_2"

3) Make new directory inside "ml_projects" directory
    "cd sorrentum_sandbox/examples/ml_projects/"
    "mkdir SorrIssue14_Team1_Implement_sandbox_for_Google_Trends"

4) Copy all the code files which you have created for your project inside this new directory.

5) Push the changes to your branch on github.

Let us know if you face and problems.

**Comment by piyush-raj-pandey** [comment]
Hi Samarth,
I've made the changes. Do let me know it was done correctly.

Thanks,
Team 1

**Comment by samarth9008** [comment]
It was done correctly.
