### ISSUE TITLE
NLP - Compute extreme returns

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#17]
This is a sub-task of #1 
 
- Load the parquet data in a pandas notebook
- Compute the close to close returns
- Do a rolling normalization so that the std dev is 1
- Look for the 1 and 5-minute movements that are larger than 3 std

**Comment by FirstSingularity** [comment]
The parquet data uses UTC as the timezone for its timestamps. Converting UTC times to EST introduces ambiguity because of daylight standard time (UTC can be 4 or 5 hours ahead). If we stick with UTC, it will be more difficult to match the data with American news, but converting it to EST will require some additional thought and code (since the standard tz_convert for datetimes does not work).

**Comment by gpsaggese** [comment]
You need to use `pd.Timestamp('2011-07-03T07:00:00-40:00').tz_convert('America/New_York')` to handle day light standard. Makes sense?

**Comment by FirstSingularity** [comment]
Yup! Using 'America/New_York' rather than 'US/Eastern' in conjunction with using the index timestamp rather than the Unix timestamp problem fixed the issue.

**Comment by FirstSingularity** [comment]
https://github.com/sorrentum/sorrentum/pull/31
