### ISSUE TITLE
Create a symlink for the whitepaper

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#199]
git supports sym links, so we want to create a link in the repo from defi/papers/{daocross_daoswap.pdf,deloc.pdf} to defi/papers/tulip.pdf

It should just be something like

```
> cd defi/papers
> ln -sf tulip.pdf daocross_daoswap.pdf
> ln -sf tulip.pdf deloc.pdf
```

and then commit and then verify that the link works on GitHub, by going to
https://github.com/sorrentum/sorrentum/blob/master/defi/papers/daocross_daoswap.pdf

FYI [smith.paul.anthony@gmail.com](https://app.asana.com/0/1204522908337620/list)

**Comment by gpsaggese** [comment]
Good job filing the bug from the Asana task.

As process I would repurpose what we used to do with the gdoc workflow to Asana
- We use Asana tasks as staging area. We file a bug to GitHub when we are ready to execute
   - We want to keep stuff in Asana as long as possible, since tasks on GitHub are easy to "lose" since there isn't a great bird-eye-view while Asana is better at this
- Add the specs from Asana to the bug so that all the context is in GitHub
- Mark the Asana task as in progress and add a link to the bug to the Asana task, and close the Asana task
- Then all the work happens on GitHub

**Comment by samarth9008** [comment]
FYI @gpsaggese, The softlink created with `ln -sf tulip.pdf daocross_daoswap.pdf` would not redirect to `tulip.pdf` instead it would just add the file path of tulip file inside the destination file that is `daocross_daoswap.pdf`. So I created a hard link with 
   `ln -sf tulip.pdf daocross_daoswap.pdf` so the user will be redirected to the `tulip.pdf` when clicked on `defi/papers/{daocross_daoswap.pdf,deloc.pdf}`
