### ISSUE TITLE
Programmatically invite people to GitHub

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#229]
We want to have a way to set the collaborators of Sorrentum using a script. Anyone who provides there github usernames should automatically be invited to the sorrentum repo.

https://docs.github.com/en/rest/collaborators?apiVersion=2022-11-28

Source of Github usernames: https://docs.google.com/spreadsheets/d/13Mxj5ZIydMQHSmJUDCpURB5w-50RPXC0AjgKWYcMZnw/edit#gid=2038824432
 
The input is a list of GitHub users and the script should find the diff between current permissions and desired permissions and then issues API call to make the user list the same to what is desired.

**Comment by patel954** [comment]
I am done writing the script and also tested with your GitHub username on one of my repository. 
This script will pull all the GitHub username from the excel sheet and send them the permission(pull, push or admin) that you want give. How do you want me to share the file by creating a branch or adding it in the comment section?

**Comment by samarth9008** [comment]
https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md

**Comment by patel954** [comment]
I have created the branch but I am not sure where should I be saving my file in which location or should I be creating a new folder?

**Comment by samarth9008** [comment]
Inside dev_scripts directory.

**Comment by samarth9008** [comment]
Did you also check if the user already has the permissions or not? As in if the user is already invited then the invitation should not be sent again. Just to avoid confusion.

**Comment by patel954** [comment]
I have used your GitHub username for testing so did you received multiple invitations? If yes then I will update the code.

**Comment by samarth9008** [comment]
Recieved only one. Did you tried multiple times?

**Comment by patel954** [comment]
Yes I did ran the code multiple after the first invitation was sent to you and also ran again right now.

**Comment by samarth9008** [comment]
Okay I only recieved once.

**Comment by patel954** [comment]
For the pull request whom do I assign to review?

**Comment by samarth9008** [comment]
Currently me.

**Comment by patel954** [comment]
Is the PR done correctly?

**Comment by samarth9008** [comment]
Yes, I will review it and let you know.

**Comment by samarth9008** [comment]
Keep your PR name like `SorrIssue229_Programmatically_invite_people_to_GitHub`.

**Comment by samarth9008** [comment]
How about we implement something like as soon as someone submits the respone our python script gets invoked and the invitation is sent automatically. Wdyt @gpsaggese ?

The steps to produce this

1. Create a Google Form and connect it to a Google Sheet where the responses will be stored.
2. Open the Google Sheet and go to "Extentions" > "App Script" to create a new Google Apps Script project.
3. Write a function in the script editor that will read the data from the response sheet and call your Python script using the subprocess module. You can use the getActiveSpreadsheet() and getSheetByName() methods to access the response sheet and retrieve the data. Here's an example of how the function might look:

```
function onFormSubmit(e) {
  var sheet = SpreadsheetApp.getActiveSheet();
  var data = sheet.getDataRange().getValues();
  var args = [JSON.stringify(data)];

  var cmd = 'python';
  var scriptPath = 'path/to/your/python/script.py';
  var process = spawn(cmd, [scriptPath].concat(args));

  process.stdout.on('data', function(data) {
    console.log(data.toString());
  });

  process.stderr.on('data', function(data) {
    console.error(data.toString());
  });
}
```
This function uses the onFormSubmit trigger to automatically run when a new form response is submitted. It then retrieves all the data from the response sheet, converts it to a JSON string, and passes it as an argument to the Python script. The spawn function from the child_process module is used to execute the Python script as a child process, with the arguments passed as command line arguments. Finally, the function listens to the output and error streams of the Python script and logs them to the console.

4. Set up a trigger in the Google Apps Script project to run the function automatically when a new form response is submitted. You can use the onFormSubmit trigger to accomplish this. To set up the trigger, go to "Apps Script" > "Triggers" and click "Add Trigger". Choose the "onFormSubmit" function and set the trigger to run "From form" and "On form submit".

5. Deploy the script as a web app to generate a unique URL that can be used to trigger the function from outside of the Google Apps Script editor. You can do this by going to "Publish" > "Deploy as web app" and following the prompts.

6. Once you have completed these steps, our Python script will be automatically invoked every time someone fills out our Google Form and the data will be read from the response sheet. You can modify the Python script to process the data however you like.

I am not sure if this would work.

**Comment by gpsaggese** [comment]
I like the idea, but the best way to proceed is to focus on the bulk of automation rather than the connective tissue and keep things idempotent.

Also adding glue logic in the spreadsheets seems a bit unreliable and messy (you can't source control it!)

Let me make a concrete example of how I would solve this problem

E.g.,
- Have a bunch of scripts that given a list of people update Gsheet permission, send GitHub invitations, etc.
   - We need a way to check what's the state, diff the state, and process the diff with the state
   - In this way each script is idempotent
- Then there is a script that loads the contributor list and sends invites to all the new people using the script above
   - Any time you run the script you are guaranteed that the system (Gsheet, GitHub) is in sync with the Contributor list
- Then we add another script that copies the data from the 2 gsheets backing up the gforms to the Contributor list

The advantages of this approach are:
- You automate the pieces and later you put them together (in this way you can start using the system automatically)
- All the code is using polling approach instead of reacting which is more reliable
- Everything is under source control without weird scripts connecting the gsheets

In any case, let's focus on the "mechanisms" to do the work and then we focus on stitching them together

Makes sense?

**Comment by gpsaggese** [comment]
Also let's do these things quickly since they are to warm up and give us some benefit in terms of productivity, but don't make us money directly :-)

**Comment by DanilYachmenev** [comment]
finally done, closing
will implement any follow-ups in the next related issue
