### ISSUE TITLE
Team5: Implement sandbox for Kibot

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#24]

**Comment by gpsaggese** [comment]
On Feb 20, 2023, at 11:57 PM, Aditi Ganesh Joshi <ajoshi18@umd.edu> wrote:

Please guide us on how to set up aws credentials in the repository. I am facing an error due to that. I am also attaching a screenshot of the same here.

<img width="770" alt="image" src="https://user-images.githubusercontent.com/33238329/220343391-e94281aa-facf-4d2d-8f8e-2b8ecf215bb8.png">
<img width="695" alt="image" src="https://user-images.githubusercontent.com/33238329/220343398-82135209-0e4e-4470-8812-d984a622577d.png">


On Feb 20, 2023, at 8:26 PM, Carlos Eduardo Puerta <cpuerta@umd.edu> wrote:

I can't speak to others but I cannot get the Kibot.py or Kibot.ipynb within research_amp/altdata to run. If I try to run the file within the folder, it cannot find the modules in the rest of the repo, and if I move it to the top level of the repo, it finds an error inin helpers.hs3 saying that s3fs is not defined. I don't really know what other steps to try to get the code to compile.

On Feb 20, 2023, at 5:49 PM, Giacinto Paolo Saggese <gsaggese@umd.edu> wrote:

Hello Team 5,

On Feb 20, 2023, at 5:36 PM, Farhad Abasahl <farhad@umd.edu> wrote:

Hello Professor,

We did try to find out about the project and here the problems we found so far;
1. This document does not provide us full information to work with.

Which document?

2. We are not able to run this Jupiter example.

What is the error?


We think that session is fine with Samarth to work on those problems. 

Kibot is a little tricky, since it doesn’t have an API and so we have implemented an example of “scraping” API for you.

In any case I’ve managed to run all the notebooks.
I’m sure Samarth can solve the problem. If things are problematic, I can jump in and help.

In any case, don’t get demotivated Team 5. These are the problems that you will find on the field, so you need to learn how to figure things out. Keep working at it. Never give up.

Good luck,
GP

**Comment by gpsaggese** [comment]
Problem found. Fixing it

**Comment by psweet** [comment]
I've tried running on a different machine and am getting an OS incompatibility. See https://stackoverflow.com/questions/61241374/attributeerror-module-os-has-no-attribute-uname

I'm still not super familiar with docker but it appears as though this should be put into a docker image and ran in a Linux VM? I know Aditi is using macOS and I think that incompatibility doesn't exist since it macOS is Unix. I'm 50/50 Windows and macOS but have not been able to get any of them to run. 

I'm going to play around with Docker but i'm still not 100% sure how to do that :)

**Comment by samarth9008** [comment]
You can try to run it on docker if you want. For python in windows you will have to use different module such as "platform".

**Comment by psweet** [comment]
helpers/hserver.py (the file erroring on Windows) has dedicated functions to detect the machine it is running; windows is not an option. Even after substituting `os.uname()` with `platform.uname()` the checks fail and the code errors out. I don't really understand enough about VMs or OS checking to fix this.

**Comment by gpsaggese** [comment]
I got the notebook to run. In few hours I will have a fix.
