### ISSUE TITLE
Convert Python - Imports and packages gDoc to Markdown

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#329]
- We need to convert a [Gdoc](https://docs.google.com/document/d/1-HGV7o546BwNIH7ekdi0yZ4lT3CBSL1Thht9QmjhIv8/edit) of Python - Imports and packages to Markdown
- Instructions on how to convert Gdocs to Markdown are [here](https://github.com/sorrentum/sorrentum/blob/master/docs/Documentation_about_guidelines.md#gdocs---markdown)
- Read about the [First Review Process](https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md)
- Lint the markdown file using the [linter](https://github.com/sorrentum/sorrentum/blob/master/dev_scripts/lint_md.sh)
- PR example is https://github.com/sorrentum/sorrentum/pull/198

FYI @DanilYachmenev

**Comment by lokashrinav** [comment]
Hello Samarth. Can you check if I converted into a markdown correctly? Feel free to correct any mistakes. I couldn't use the linter since I don't have access to the google doc: 

<p style="color: red; font-weight: bold">>>>>>  gd2md-html alert:  ERRORs: 0; WARNINGs: 1; ALERTS: 0.</p>
<ul style="color: red; font-weight: bold"><li>See top comment block for details on ERRORs and WARNINGs. <li>In the converted Markdown or HTML, search for inline alerts that start with >>>>>  gd2md-html alert:  for specific instances that need correction.</ul>

<p style="color: red; font-weight: bold">Links to alert messages:</p>
<p style="color: red; font-weight: bold">>>>>> PLEASE check and correct alert issues and delete this message and the inline alerts.<hr></p>


TODO(gp): Consolidate here any other rule from other gdoc


# # Goals of packages

The goal of creating packages is to:



* simplify the import from clients
* hide in which file the actual code is, so that we can reorganize the code without having to change all the client code
* organize the code in related units
* make simpler to avoid import loops by enforcing that there are no import loops in any module and no import loops among modules

E.g., referring to package from a different package looks like

```

import dataflow.core as dtfcore

dtfcore.ArmaGenerator(...)

```

Importing the specific file:

```

import dataflow.system.source_nodes as dtfsysonod

dtfsysonod.ArmaGenerator(...)

```


## ## Circular dependency (aka import cycle, import loop)

The simplest case of circular import is a situation when in lib `A` we have `import B`, and in lib B we have `import A`.

The presence of circular imports can be checked with an invoke i lint_detect_cycles. By default it will run on the whole repo, which takes a couple of minutes, but it will provide the most reliable and thorough check for circular imports.


## ## Rules for imports

We follow rules to avoid import loops:



1. Code inside a package should import directly a file in the same package and not use the package
* E.g., im_v2/common/data/client/data_frame_im_clients.py 

    	**Good**


    	```


    	import im_v2.common.data.client.base_im_clients as imvcdcbimcl


    	```


        **Bad**


        ```


        import im_v2.common.data.client as icdc


    	```

2. Code from a package should import other packages, instead of importing directly the file	
3. We don't allow any import loop that can be detected statically (i.e., by inspecting the code without executing it)
* This guarantees that there are no dynamic import loops, which are even more difficult to detect and disruptive
4. We allow only imports at module level and not inside functions
* We don't accept using local imports to break import loops, unless it's temporary to solve a more important problem
5. We allow nested packages 
    * TODO(gp): Clarify the rules here
6. We don't want to abuse of packaging by creating too many of them
* Rationale:
* There is overhead in organizing and maintaining code in packages and we want to pay the overhead only if we get enough benefit from this
7. We specify a short import in the `__init__.py` file for a package manually because linter cannot do it automatically yet. 
* We use first letters to build a short import and try to keep it less than 8 chars long, e.g., `​​im_v2.talos.data.client` -> `itdcl`
* We insert an import docstring in the `__init__.py` file manually and then we use the specified short import everywhere in the codebase. E.g.,

        ```


        """


        Import as:


        import im_v2.talos.data.client as itdcl


        """


        ```

* 
* 


## ## How to import code from unit tests

To avoid churning client code when code is moved among files, we allow unit tests to both:



1. import package when testing code exported from the package

E.g., in market_data/test/market_data_test_case.py you can import the package even if it's included

import market_data as mdata

… mdata.AbstractMarketData …



2. import directly the files with the code and not the package

E.g.,

import market_data.abstract_market_data as mdabmada

… mdabmada.AbstractMarketData …

To justify 1. one can argue that unit tests are clients of the code and should import packages like any other client.

To justify 2. one can interpret that unit tests are tied to specific files so they should be kept in sync with the low-level code and not with the public interface. In fact we already allow unit tests to call private functions, acknowledging that unit tests are not regular clients.

Given that both explanations are valid, we allow both styles.


### ### Common unit test code

Unit tests should not import from each other



* If there is common code should go in libraries inside or outside `test` directories
    * E.g., we use `foobar_example.py` files containing builders for mocks and example of objects to be used by tests
    * E.g., we use `test/foobar_test_case.py` or `test/foobar_utils.py`
* In other terms test files are always leaves of the import graph


# # Package/lib hierarchy and cycle prevention

Static import cycles can be detected by the invoke `lint_detect_cycles`. 

To prevent import cycles, we want to enforce that certain packages don't depend on other packages



* E.g., `helpers` should not depend on any other package, besides external libraries
* `core` should only depend on `helpers`
* `dataflow` should only depend on `core` and `helpers`
* These constraints can be expressed in terms of "certain nodes of the import graph are sources" or "certain edges in the import graph are forbidden" 

We also want to enforce that certain libs don’t import others within a single package. For example, in `helpers` the following hierarchy should be respected: 



1. hdbg (should not depend on any other helper)
2. hintrospection, hprint (should depend only on hdbg for assertion)
3. henv, hsystem, hio, hversio (this is the base layer to access env vars and execute commands)
4. hgit (Git requires accessing env vars and system calls)

A library can only import libs that are “below” it or on the same level. E.g. `henv` can import `hdbg`, `hprint` and `hio`, but it cannot import `hgit`. NB: while importing a lib on the same level, make sure you are not creating an import cycle.

In addition, keep in mind the following rules to prevent import cycles:



* Any import inside a function is just a temporary hack waiting to create problems.
* Any time we can break a file in smaller pieces, we should do that since this helps control the dependencies.


# # Anatomy of a package

TODO(gp): Let's use `dataflow` as a running example

A package has a special __init__.py exporting public methods

**Comment by samarth9008** [comment]
@lokashrinav Whats the update on the task? Any questions? ETA pls?

**Comment by lokashrinav** [comment]
@samarth9008 Hello Samarth, I'll have it done by the end of the day.

**Comment by lokashrinav** [comment]
@samarth9008 Hello Samarth, I just pushed my code through a branch. Can you make sure that I pushed it correctly using git? I don't have that much experience when it comes to creating branches/pushing code from branches. Also, can you make sure that I did the linting correctly? Thanks

**Comment by lokashrinav** [comment]
@DanilYachmenev Alright thanks! Yup. I made sure to file a PR, which was reviewed by Samarth some time ago. I was just making sure, so that everything would run correctly.

**Comment by DanilYachmenev** [comment]
> @DanilYachmenev Alright thanks! Yup. I made sure to file a PR, which was reviewed by Samarth some time ago. I was just making sure, so that everything would run correctly.

Could you share a link to it here?
part of the process, read the full doc
https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md#mention-the-issue

**Comment by lokashrinav** [comment]
@DanilYachmenev Thanks!. I just did it. Also, on another note, have you ever gotten an error when building the thin environment. For some reason, I can't do it. I'm using a Linux OS, and when I run the command, my terminal disappears. Afterwards, when I run the command to activate it, an error pops up: "ERROR: Can't find '/home/user/venv/amp.client_venv/bin/activate". Do you know what I should do? By the way, I CD'd into ~/src/sorrentum1

**Comment by DanilYachmenev** [comment]
@lokashrinav it is vary hard to debug anything without seeing the cmd you used and complete error logs
pls post them here

**Comment by lokashrinav** [comment]
@DanilYachmenev Alright. I this command to build the thin environment: "source dev_scripts/client_setup/build.sh" - This is the command that causes my running terminal to stop running.
And when I run this command to activate the environment "source dev_scripts/setenv_amp.sh", this pops up: "
# Activate virtual env '/home/user/venv/amp.client_venv/bin/activate'
ERROR: Can't find '/home/user/venv/amp.client_venv/bin/activate'

**Comment by DanilYachmenev** [comment]
I think you need to build the env first
`> dev_scripts/client_setup/build.sh`

**Comment by lokashrinav** [comment]
@DanilYachmenev Oh. Did I have to remove the source part of the command? because I ran the build command that you mentioned in the terminal and put it in the comment above.

**Comment by DanilYachmenev** [comment]
read the cmd more carefully and set-up instructions as well
you'll see that it is a different cmd

and please, practice independent search for answers
I'd like to answer your questions but when they are really the problem that you could've not find in docs or notice yourself
cant chat here on every small step

**Comment by DanilYachmenev** [comment]
hmm, interestingly, no I see that I've overlooked what you wrote above
indeed, `build.sh` is being run without source
so you were right, sorry for claiming the opposite

although, my last comment is still valid

**Comment by DanilYachmenev** [comment]
done
