### ISSUE TITLE
Write a function that extracts the latest available universe

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#362]
In `im_v2/common/universe/universe.py` we have function that allow us to get a specific vendor universe

However, we want to be able to extract the latest available vendor universe

For this we need to:

1) Create a helper function `_get_all_vendor_universe(vendor: str, mode: str) -> List[str]` (and expose it in `_get_universe_file_path`)
2) Write a function `get_latest_vendor_universe(vendor: str, mode: str) -> str` (see `_get_universe_file_path` when `if version is None:`, use the logic from there)
We should aim at the latest universes that follow the pattern `universe_v*.json`, others are just supplimentary 
3) Add unit tests in `im_v2/ccxt/universe/test/test_universe.py` and `im_v2/mock1/universe/test/test_mock1_universe.py` (can do in a separate PR if wanted)

FYI @samarth9008

**Comment by christyanthony** [comment]
@DanilYachmenev ,

Please let me know if my understanding is correct.

- First I need to create a helper function `_get_all_vendor_universe(vendor: str, mode: str) -> List[str]` and make it accessible in `_get_universe_file_path` so that it can be called when needed to obtain all the vendor universe file paths. I suppose the modes would be download and trade

- A new function `get_latest_vendor_universe(vendor: str, mode: str) -> str` needs to be created and the logic related to latest version needs to be written in this function, taking the example from `_get_universe_file_path` for version is none.

- I initially thought that both these newly created functions should be called in `_get_universe_file_path` seeing the example of `_get_universe_dir` and `_get_universe_files`. But the requirement didn't ask for the exposure of `get_latest_vendor_universe` in `_get_universe_file_path`. So here are you expecting to call `_get_universe_file_path` in `get_latest_vendor_universe`.

- As for the unit tests for the newly created functions, can you please provide more info 

Please correct me if I am wrong and also let me know if I missed anything.

**Comment by DanilYachmenev** [comment]
@christyanthony thx for detailed clarification questions
now I actually see that this task is much bigger than I expected, so lets even not do unit tests here

Also, after the integration it seems that `_get_all_vendor_universe()` is already presented by `_get_universe_files()` so no need to care about it much

However, use it to create `get_latest_vendor_universe()`
And I here want to update the interface for you to clarify

```
def get_latest_vendor_universe(vendor: str, mode: str) -> Dict[str, List[str]]:
    """
    Load the latest universe specific of a vendor and mode.

    :param vendor: vendor to load data for (e.g., CCXT/Talos)
    :param mode: download or trade universe
    :return: latest universe as a nested dictionary of
      exchange name (e.g., binance) to list of symbols e.g.,
        {
            "CCXT": {
                "binance": [
                "ADA_USDT",
                "AVAX_USDT",
                "BNB_USDT",
                "BTC_USDT",
                "DOGE_USDT",
                "EOS_USDT",
                "ETH_USDT",
                "LINK_USDT",
                "SOL_USDT"
                ],
                ...
            }
        }
    """
```

So you need to return not a path, but a universe
And the tricky part here is that apart from `get_vendor_universe()~ we need to find the latest universe automatically
for inspiration you can use the approach used in `_get_universe_file_path()` under `if version is None:` clause, but it may give you just the latest universe path, so you need to extract its content

**Comment by christyanthony** [comment]
@DanilYachmenev , could you please confirm this?

So we are creating function `get_latest_vendor_universe()` to get/extract the content of the latest universe path by utilizing the function `_get_universe_files()`. We are not creating `_get_all_vendor_universe()` as the functionality is already available `_get_universe_files()`.

**Comment by DanilYachmenev** [comment]
> _get_universe_files

Well, after the repo integration I actually see that this task is not really relevant anymore
So it is good that you've made clarification questions, especially considering previous task
Sorry for backs-and-forth, takes time to find a right balance between task complexity and necessity

I've spend time to think of a valid task for you
See https://github.com/sorrentum/sorrentum/issues/373

discard this one, `get_universe_versions()` can be used to get the latest universe with comparable ease

**Comment by christyanthony** [comment]
Lol. 
I actually thought about  `get_universe_versions()`, but didn't mention thinking we might be extending something more using the new function.

Will start working on #373 .
