### ISSUE TITLE
Unit test `get_df_from_iterator`

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#373]
Add a unit test for `get_df_from_iterator()` from `helpers/hpandas.py`

The tests should go to `amp/helpers/test/test_hpandas.py`

What you need to do:
1) Create an `Iterator` obj with 3 small dataframes in it
2) Implement `# TODO(gp): @all make a copy of `iter_` so we don't consume it.`
3) Write a unit test and use signature approach to compare outcomes. See `TestDropDuplicates` for reference (how resulting dataframes are compared)
4) Check that input `Iterator` object has not expired after the test (check its length)

Read https://github.com/sorrentum/sorrentum/blob/master/docs/Unit_tests.md carefully
Implement a draft PR and address your questions there so we have some code to discuss on

FYI @samarth9008

**Comment by christyanthony** [comment]
@DanilYachmenev ,

I believe there are 2 tasks that needs to be done, one in the function `get_df_from_iterator` and the second to create a unit test #373. Please find the elaboration below

- First one is to create an Iterator object with 3 small dataframes in the function `get_df_from_iterator` and also make a copy of `iter_` so that it won't be consumed by the function 

- The second one is to create/add unit test test for the function and also compare the outcomes using signature approach.

- Also, check on the input object `iterator` by its length after the test.

Could you please confirm and let me know if there's anything missing.

**Comment by DanilYachmenev** [comment]
@christyanthony these are all the points of this task basically, yes
some clarifications
- copy of `iter_` that won't be consumed by the function - this is the major change right in the function. At the endo of the function body (before `return`) add an assert that `iter_` retained the same length
- Add a unit test using signature approach. Iterator with 3 dataframes should be used for the test, not in the function
