### ISSUE TITLE
Rename unit test classes in `test_hpandas.py`

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#377]
Follow-up from https://github.com/sorrentum/sorrentum/pull/376#discussion_r1249685912

Unit test classes names in `amp/helpers/test/test_hpandas.py` are not following the conventions from the current documentation
https://github.com/sorrentum/sorrentum/blob/master/docs/Unit_tests.md#naming-and-placement-conventions

IMO it can be a good first task for a student to rename the test classes accordingly
Via `replace_text.py` ofc

@gpsaggese wdyt? If agreed, there are actually other test files that are not following to convention so multiple issues like this one could be assigned to interns as well

FYI @samarth9008

**Comment by gpsaggese** [comment]
Actually I think the convention has evolved (I've updated the doc) and the code was actually correct.

IMO renaming are not great for interns, since they touch a lot of points of the code, are difficult to do across many repos, and are difficult to integrate.
Unit tests are better bang for the buck.

I would skip this.

**Comment by DanilYachmenev** [comment]
not needed then, closing, thx!
