### ISSUE TITLE
Convert Design Philosophy gDoc to Markdown

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#399]
- We need to convert a [Gdoc](https://docs.google.com/document/d/1Lb8mlquRW76NobFeP5RFw0FbDOaY6UQEDwbbSxLsZGE/edit#heading=h.lxgxcj88txcw) of Design Philosophy to Markdown
- Instructions on how to convert Gdocs to Markdown are [here](https://github.com/sorrentum/sorrentum/blob/master/docs/Documentation_about_guidelines.md#gdocs---markdown)
- Read about the [First Review Process](https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md)
- Lint the markdown file using the [linter](https://github.com/sorrentum/sorrentum/blob/master/dev_scripts/lint_md.sh)
- PR example is https://github.com/sorrentum/sorrentum/pull/198
- Create markdown in `docs` folder.
- Add a link to this file to `sorrentum/docs/README.md` in `Learn how to become efficient at developing` section

FYI @samarth9008

**Comment by Dylan-Celli** [comment]
Minor bug noticed with 
`> ../dev_scripts/convert_docx_to_markdown.py --docx_file "Design Philosophy.docx" --md_file Design_Philosophy.docx`
Adding the quotes to make the docx file a literal string causes the command to fail, the command worked after renaming the file to `Design_Philosophy.docx` and not putting the filename in quotes.

**Comment by Dylan-Celli** [comment]
When I used the `dev_scripts/convert_docx_to_markdown.py` it added a new line after every bullet point. I looked at the other md files and saw that they did not have the new lines after every bullet point so I removed the new lines. Should I have kept the new lines in?

Additionally, after converting all the hyperlinks had an add `<span>` html tag attached to them, the links still worked and the tag did not appear in the md preview but I removed the tags because I thought they were unnecessary. Should I add these back in?

Finally, the link associated with [Measure seven times, cut once (Russian proverb)](https://docs.google.com/document/d/1R6jhFDbZKvyDdbnSQ9DA_N8417YF13hMI_Uw4quO4Xk/edit#heading=h.47lm09d3bzcd) goes to a google doc that the reader does not have access to.

**Comment by samarth9008** [comment]
> When I used the `dev_scripts/convert_docx_to_markdown.py` it added a new line after every bullet point. I looked at the other md files and saw that they did not have the new lines after every bullet point so I removed the new lines. Should I have kept the new lines in?

No. We don't want extra space.

> Additionally, after converting all the hyperlinks had an add `<span>` html tag attached to them, the links still worked and the tag did not appear in the md preview but I removed the tags because I thought they were unnecessary. Should I add these back in?

If the links are working than its fine.
 
> Finally, the link associated with [Measure seven times, cut once (Russian proverb)](https://docs.google.com/document/d/1R6jhFDbZKvyDdbnSQ9DA_N8417YF13hMI_Uw4quO4Xk/edit#heading=h.47lm09d3bzcd) goes to a google doc that the reader does not have access to.

Thats fine.

**Comment by yiyunlei** [comment]
> Additionally, after converting all the hyperlinks had an add `<span>` html tag attached to them, the links still worked and the tag did not appear in the md preview but I removed the tags because I thought they were unnecessary. Should I add these back in?

This HTML tag exists because the original Gdoc actually has an underline under the link, and it will show when you click the link in Git Hub. But you can also delete it since it's not a big deal. 
<img width="721" alt="image" src="https://github.com/sorrentum/sorrentum/assets/42398651/858fbebe-8eda-44b2-be15-89b59d8a2184">

**Comment by yiyunlei** [comment]
> Minor bug noticed with `> ../dev_scripts/convert_docx_to_markdown.py --docx_file "Design Philosophy.docx" --md_file Design_Philosophy.docx` Adding the quotes to make the docx file a literal string causes the command to fail, the command worked after renaming the file to `Design_Philosophy.docx` and not putting the filename in quotes.

> When I used the `dev_scripts/convert_docx_to_markdown.py` it added a new line after every bullet point. I looked at the other md files and saw that they did not have the new lines after every bullet point so I removed the new lines. Should I have kept the new lines in?

Thanks for pointing those out. I'll update the document accordingly.

**Comment by yiyunlei** [comment]
The filename can be put in quotes, but it can't contain any white spaces.

**Comment by Dylan-Celli** [comment]
The link associated with the text "these slides" under `## Tips from a pro` is no longer valid. Where can I find the the slides so I can fix the links?
broken link: https://static.googleusercontent.com/media/research.google.com/en/people/jeff/stanford-295-talk.pdf

I tried looking up the slides and found Jordan Dean's Stanford page but it seems that the lecture slides link is broken there as well.
Stanford page: https://talks.stanford.edu/jeff-dean-tensorflow-overview-and-future-directions/

**Comment by samarth9008** [comment]
Just use this link for now. Mention about this in your PR.
