### ISSUE TITLE
LIN manual flow experiment

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#410]
We want to implement manually and document the typical use case

https://docs.google.com/document/d/1_A50Zf5ByRMZtcoufQooenaQuuHw4GMrxCoaR4Kf3kE/edit#heading=h.9msl4rrbxg33

Then we want to automate using Python.

FYI: @samarth9008

**Comment by sonniki** [comment]
An observation about creating a new Phantom manually (through the GUI): at some point it will prompt you to provide a [session cookie](https://support.phantombuster.com/hc/en-us/articles/360007071719-Connect-your-Phantom-via-session-cookies), and it is account- and session-specific, as far as I understand. So the only option for a user who is creating a Phantom is to provide their own account's cookie (even if they are logged in in PhantomBuster as someone else). It works, although, if their network on LinkedIn does not cover certain people, they will be not included in the Phantom output, like so: 

![image](https://github.com/sorrentum/sorrentum/assets/22771988/c5c0ff83-643f-4e10-acba-26f09a10df86)

**Comment by sonniki** [comment]
The whole process of creating and running Phantoms (Search Export & Profile Scraper) manually from the GUI is pretty intuitive, not sure it needs a description here.
The only interesting observation I wanted to point out is that it is possible to give the Profile Scraper a link to the gsheet and specify the column with the URLs to scrape, which is handy because this is how we store the output of Search Export (and its filtered counterpart). Like so:

![image](https://github.com/sorrentum/sorrentum/assets/22771988/4e84b501-09c0-43e3-a405-8f79a51b8e9f)

**Comment by gpsaggese** [comment]
Sounds good. @yiyunlei and I will re-run it manually with more input searches to work the system.

The tricky part IMO is if we can automate the flow a bit so there is less clicking, and also when the scraping takes days and it's easy to forget what stage one is at.

**Comment by sonniki** [comment]
> Sounds good. @yiyunlei and I will re-run it manually with more input searches to work the system.
> 
> The tricky part IMO is if we can automate the flow a bit so there is less clicking, and also when the scraping takes days and it's easy to forget what stage one is at.

Sure! Is there anything else for me to try or report on this task, since I went through this whole process already?

**Comment by yiyunlei** [comment]
> Using Gsheet as input is fine. Saving output as Gsheet is a bit more complicated, e.g., @yiyunlei found out this approach https://support.phantombuster.com/hc/en-us/articles/360007125739-View-your-Results-with-Google-Spreadsheets
> 
The part of saving CSV files to Gsheet hasn't been done yet, right?

**Comment by sonniki** [comment]
> The part of saving CSV files to Gsheet hasn't been done yet, right?

In my experiments I have been converting them manually. BTW there is also a possibility, if we already have a csv file, to open it with pandas and then automatically convert it to a gsheet with `gspread_pandas`. The caveats are 1) the csv file has to be exported from phantombuster to a place accessible to our code and I don't know how to do it automatically; 2) to save a df into a gsheet with `gspread_pandas`, we need to specify the name of the target gsheet and it has to already exist on the drive, which, again, not sure if can be done automatically.

**Comment by yiyunlei** [comment]
> Sure! Is there anything else for me to try or report on this task, since I went through this whole process already?

I am trying to sort out the entire automation process, documenting the steps needed to be done and existing issues. I will need you to take a look at it later and maybe give some feedback.

**Comment by yiyunlei** [comment]
I found some minor issues in the resulting Gsheets. @sonniki 

1. from [search_retired1.search_export.gsheet](https://docs.google.com/spreadsheets/d/1iJRfHsnVHBYZp3P1wsPEvNs2nooFYSkBXxfs3illbEY/edit#gid=0) to [search_retired1.search_export.filtered.gsheet](https://docs.google.com/spreadsheets/d/1iJRfHsnVHBYZp3P1wsPEvNs2nooFYSkBXxfs3illbEY/edit#gid=0), 
IMO we don't have to filter out the location such as DC and VA, since they all near the location we put in the search:
<img width="329" alt="image" src="https://github.com/sorrentum/sorrentum/assets/42398651/544389e2-c8ea-47ef-97e1-a478bf14542c">

2. We are losing some results from [search_retired1.profile_export.gsheet](https://docs.google.com/spreadsheets/d/10xI-iDMMUN9kJKm-C5U2TXh3-haPt2VFQe90XoAcLeM/edit#gid=1248257226) to [search_retired1.profile_export.filtered.gsheet](https://docs.google.com/spreadsheets/d/19aLXyLDNk8MyczOdenriGeOogEaC0LDR29bISY64-QA/edit#gid=0), and they are not duplicate.

We are losing some useful results in the whole process.

FYI @gpsaggese

**Comment by sonniki** [comment]
@yiyunlei you are definitely right --- I was just doing some random ("bogus", as it was called in the instructions in the [gdoc](https://docs.google.com/document/d/1_A50Zf5ByRMZtcoufQooenaQuuHw4GMrxCoaR4Kf3kE/edit#heading=h.9msl4rrbxg33)) filtering (based on location in the search export notebook and based on keywords in the profile scraper notebook), with the only purpose to give an illustration of how filtering can be done in the future experiments. 

These gsheets do not represent the "actual" query results anyway because they have been collected with my LinkedIn cookie, which is not covering lots of people from outside of my network:)

**Comment by yiyunlei** [comment]
@sonniki, thank you for the clarification! I was confused at first, but I understand it now. :) I missed the point about 'bogus'. I also looked through the code again, and they are excellent examples.

**Comment by samarth9008** [comment]
Can we sprint, epic and estimate to it

**Comment by gpsaggese** [comment]
Done

**Comment by samarth9008** [comment]
I believe this is outdated so closing it. Will re-open if required.
