### ISSUE TITLE
Add more recent crypto NLP data

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#42]
@sonniki can we save in https://drive.google.com/drive/folders/1nHfXUvVyqsTFTvIbJ5tIUh0FkJ3duN4P some data for crypto from RP? Can we a year of data from 2021?
Do you know if the new edge format has the same schema as the old data? I believe so.

**Comment by sonniki** [comment]
> Can we a year of data from 2021?

No problem. Which tokens exactly?

> Do you know if the new edge format has the same schema as the old data? 

The core fields are mostly the same, but there are changes. There are a lot of new fields, now there are 80+ of them in total. Some of the old fields got renamed to make their meaning more explicit because more granularity was added (e.g. a million different sentiment scores). So it's better to use the new documentation to work with the new data for sure. 
Also, do you want me to save all the fields for this 2021 sample or some selection?

**Comment by gpsaggese** [comment]
1) We can do the ~top 10 coins, but no reason to be too precise. 10 large cap is good enough.

2) Interesting. Let's use the new data then. Can you pls put also the new documentation in PDF there?
You can create a new dir "Edge" or whatever is called now. Do we have also the text of the headline?

3) Yes, 2021 data is good (assuming it's not an insane amount of GB), otherwise we can do a few months. Your call.

Thx!

**Comment by sonniki** [comment]
Created a dir [here](https://drive.google.com/drive/folders/1pc7l9OjLXe5l1_9eVFCq6zfclfnzn8Yy) and put there 
- the documentation in PDF (yes, the text of the headline is there -- field TITLE, as well as the text of the detected event itself, when applicable -- field EVENT_TEXT). 
- RP data for top 10 coins from CoinMarketCap from 2021-01-01 to 2021-12-31, in CSV. In total there are ~2M rows, about 1GB in size. I downloaded all 85 fields, but some of them can be dropped to save space (e.g. technical ones like BYTE_COUNT, or ones that are irrelevant for crypto like EARNINGS_RELEASE_SENTIMENT).

**Comment by sonniki** [comment]
@gpsaggese Can be closed?
