### ISSUE TITLE
Upload the local csv to google spreadsheet

### ISSUE THREAD

**Issue by yiyunlei** [sorrentum/sorrentum#512]
- Interact with Google API to upload the local CSV to Google spreadsheet.
    - Use gspread_pandas
- After uploading to gsheet, delete the tmp file.

**Comment by yiyunlei** [comment]
- ETA: Next Tuesday(2023-08-08)
  - Implement function and add to the notebook.

**Comment by gpsaggese** [comment]
When do we use local files? Can we always read / modify gsheets without ever copying to local files?
Copying things around makes things more difficult, since you have multiple copies which creates confusion

The approach I suggest is to create a gsheet dir and then each step (notebook or PB) reads one gsheet as inoput and generates another one without overwriting.

Makes sense?

**Comment by yiyunlei** [comment]
This is the second step to extract PB results to gsheet. #487 
(We use local files only in this case)
- I implemented the first step to get PB results from the PB server to local storage. #515 
- After downloading to local, we need to upload the result CSVs to gsheet so that we can use them as input for other steps.
- We don't have to copy these files manually, as it will automate the download of CSV files and upload to gheet after I implement these two steps.

**Comment by gpsaggese** [comment]
Clear explanation. Now I understand.

Just make sure to download to local storage as tmp file, upload to gsheet, and delete the tmp file.
The idea is to avoid duplicated data

**Comment by yiyunlei** [comment]
- ETA: Today(2023-08-09)
    - Finish up PR #525
