### ISSUE TITLE
Get more emails using PB

### ISSUE THREAD

**Issue by yiyunlei** [sorrentum/sorrentum#526]
Can we use a better PB to get the email, e.g., start with PhantomBuster

Start with PhantomBuster and see how many emails in Search5 we get
If yield is low we can experiment with more expensive services
Can we run ¼ of Search5 (filter top 25%) and run the flow to get emails
How many emails do we get?
ETA: 2 days

**Comment by gpsaggese** [comment]
From TG

Yiyun Lei, [8/8/23 5:13 PM]
I just ran the Phantom with email discovery once and got the emails of 6 out of 10 people. This feature is pretty good.

Yiyun Lei, [8/8/23 5:14 PM]
I will send you the result of how many emails we can get out of 50 people tomorrow.

Yiyun Lei, [8/8/23 5:15 PM]
Because it’s twice as slow to run the Phantom with email discovery, so we will need ~4 days to get the emails of ~200 people.

GP Saggese, [8/8/23 5:29 PM]
Sg. I think we want to "filter" as many people as possible in the first phase

**Comment by gpsaggese** [comment]
Let's split the actions:
1) understand how good is the new PB to get the emails. We can just run on a subset, e.g., 50 people, to get a sense of the hit rate
2) we should filter out as many people after the first stage so that the workload for phase 2 is minimal

**Comment by yiyunlei** [comment]
For the second one:
Do you mean to filter out the people whose emails we can't get?
________________________________

**Comment by gpsaggese** [comment]
For the second one I mean filtering out the people that are "false positives" on step 1 (the search query), i.e., that they are not likely good candidates as mentors, so that we don't have to extract profiles and emails for them which is slow.

The fact is that Search5 is pretty "precise" in the sense that a high percentage of the results are good mentors

Some false positives (people that we should filter out in step1) in https://docs.google.com/spreadsheets/d/1XJtEwn_Nu46xpQDCpJaqTHs0auY2CeOgDDJkF0s52NQ/edit#gid=1827579557 are
- Executive Assistant
- Lead Graphic Designer 
- Customer Service Representative
- Shift Leader
- Clinical Nurse

The problem is that it's not easy to filter out the ones automatically. Maybe we can start doing this by hand and then try to generalize. Here ChatGPT might even help to do some sort of filtering based on keywords and synonyms :-)
In any case one step at the time

Makes sense?

**Comment by yiyunlei** [comment]
Yes,very clear. I will work on this tomorrow.

**Comment by yiyunlei** [comment]
- ETA: Friday(2023-08-11)
- Work of Today:
   - PB email discovery experiment (Get hit rate). 
   - Filter out as many people as possible in the first phase.

**Comment by yiyunlei** [comment]
@gpsaggese 
Get 37 emails out of 59 people. hit rate ~ 2/3.
You can check the column **mailFromDropContact** in this gsheet.
[sn_search5_pb_email_discovery.search_export](https://docs.google.com/spreadsheets/d/1GRr5gTYVtb23f--lpGiwoFvTjHhbkEzwNe4vtUE2pIM/edit#gid=0).

According to the doc from Phantombuster:
https://support.phantombuster.com/hc/en-us/articles/4414991910034-Email-discovery-credits
Changing our current Plan won't change the hit rate, it just changes how many people we can attempt to find their emails.
With our current plan (starter plan, we can attempt to find emails from 500 people per month.)

**Comment by gpsaggese** [comment]
60% is not bad.
To get a higher hit rate we can use a better email retrieval service than PB, but it's just about paying and changing an option in the PB. Let's keep going using PB for now and let's see if we can get search5 complete.

**Comment by yiyunlei** [comment]
ETA: Today (2023-08-14)
- Finish up work of manual filter for search export and email collection.

**Comment by yiyunlei** [comment]
Final result:
https://docs.google.com/spreadsheets/d/1j_kD3o5ZQ4CPDwSM5xPeALF79DpRBwm1C99Djxcn1es/edit?usp=sharing
Get 55 emails out of 105 people. (After manual filter.)

**Comment by yiyunlei** [comment]
@gpsaggese 
I think you can begin the email-sending process using this [Gsheet - sn_search5.step4.profile_export_filtered](https://docs.google.com/spreadsheets/d/1j_kD3o5ZQ4CPDwSM5xPeALF79DpRBwm1C99Djxcn1es/edit?usp=sharing).

I manually filtered the data in this gsheet:
https://docs.google.com/spreadsheets/d/19DxKKFqvIqStVYPl2wVvxbwXUgWmYupIHX89t0JbUP8/edit#gid=0

I used the help of ChatGPT to do the filtering job:
If ChatGPT indicated that someone wasn't a suitable mentor, I double-checked. If I agreed with ChatGPT, I marked them as "False" and filtered them out in the [Gsheet - sn_search5.step4.profile_export_filtered](https://docs.google.com/spreadsheets/d/1j_kD3o5ZQ4CPDwSM5xPeALF79DpRBwm1C99Djxcn1es/edit?usp=sharing).

Due to the limitations of the ChatGPT API, I also did some filtering entirely by hand.

I can't guarantee 100% accuracy, but it's close.

**Comment by gpsaggese** [comment]
Very interesting approach. How did you automate populating the gsheet with ChatGPT? Did you call it from Python? There are packages to interface.

1) FYI we have a license of ChatGPT that we can use
2) We could score only people with email to make things faster
3) A failure mode of the classification problem is that ChatGPT does its work correctly but the query is "incorrect" since it doesn't capture our true intention (either because it's not properly formulated or because we don't have a correct understanding of the problem).
In this case the right approach would have been to "score" before seeing what ChatGPT said but checking if the candidate is a good mentor or not (based on our understanding), instead of checking whether what ChatGPT said made sense. 
In any case those are problems we can look into later. 

In any case (besides thorny epistemological issues) we can certainly start sending emails. Very good job!

**Comment by yiyunlei** [comment]
I use a ChatGPT Gsheet extension to call ChatGPT. Actually, it's inconvenient because I can only use 3~5 API calls per minute and the extension can't run it automatically. Therefore, I have to click many times. I could try Python packages next time.

I was not just checking whether what ChatGPT said made sense, I also checked the information from the original data to make decisions.

**Comment by gpsaggese** [comment]
Done
