### ISSUE TITLE
Centralize input validation when running ETL scripts

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#538]
We need to centralize checking logical dependencies between values of various arguments for ETL scripts.

To start we need to:
- [x] Create `im_v2/common/data/qa/validate_input_args.py` to store the function for the task
- [x] Create `validate_vendor_arg(vendor: str, args: argparse.Namespace) -> ivcdexex.Extractor` in the newly created file that will be doing what is done now from https://github.com/sorrentum/sorrentum/blob/master/im_v2/common/data/extract/download_bulk.py#L77 up to line 95
- [x] Replace the mentioned code by the newly created `validate_vendor_arg()`

FYI @jsmerix

**Comment by samarth9008** [comment]
Please assign an EPIC to it.

**Comment by gpsaggese** [comment]
@samarth9008

Two refinements of the rules:
1) let's ignore the EPICs in sorrentum, and use EPICs only in cmamp
2) When an issue is closed without an EPIC, we reopen it so that we don't forget to set EPIC and estimate.
Of course, let's only do it moving fwd and not retroactively.

Can you pls update the EpicMeister doc with these 2 rules?
