### ISSUE TITLE
Create a notebook showing Chainlink off-chain data and computation

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#55]
We want to understand how to set up an off-chain data and computation
https://chain.link/education-hub/off-chain-data

E.g., store data off-chain and retrieve it and create a simple function (it can be anything, even a simple addition as long as it's in Python) but off-chain

**Comment by tamriq** [comment]
Here we have two options:
1) [Chainlink Functions](https://docs.chain.link/chainlink-functions/)
2) [Chainlink Any API](https://docs.chain.link/any-api/introduction/#:~:text=Connecting%20to%20any%20API%20with,complexity%20of%20building%20smart%20contracts.)

Chainlink functions is currently in beta, so we can't use it. But the functionality is very promising, we should definitely consider it as an option in the future. From documentation:
> Chainlink Functions is available on testnet only as a limited BETA preview to ensure that this new platform is robust and secure for developers. While on testnet and in BETA, developers must follow best practices and not use the BETA for any production application or secure any value. Chainlink Functions is likely to evolve and improve. Breaking changes might occur while the service is in BETA. Monitor these docs to stay updated on feature improvements along with interface and contract changes. 

Chainlink Any API is a good option for us. In this case we need to create our own web services that will meet our goals, e.g. make specific computations.

**Comment by tamriq** [comment]
In fact, to implement off-chain computations with Any API, we need to run our own web service to have some url Chainlink oracle can interact with. We can use AWS for this purpose, but it would be good to sync about it, since I'm not highly proficient in web services stuff. 
Anyway let's define the functionality we want to get as a result:
1) Store orders list off-chain 
2) Calculate total sell/buy amount off-chain
3) Calculate but/sell proportion off-chain
