### ISSUE TITLE
Create an external adapter to get TWAP/ VWAP prices for DaoSwap

### ISSUE THREAD

**Issue by tamriq** [sorrentum/sorrentum#66]
As we discussed, we want to have three price sources for DaoSwap:
1) Chainlink Price Feed (already implemented). In fact, the price in these feeds is typically derived from multiple sources, including different exchanges and data providers.
They do not directly use TWAP or VWAP as part of aggregation. As far as I understand, they do use a sophisticated aggregation mechanism that takes into account various factors, including the volume, liquidity, and quality of data sources. 
2) TWAP (not implemented).
3) VWAP (not implemented). 

While Chainlink Price Feeds do not explicitly provide TWAP or VWAP data, we should create a custom solution with [chainlink external adapters](https://docs.chain.link/chainlink-nodes/external-adapters/external-adapters/). About external adapters: 
 - An external adapter for Chainlink is a small program or service (in fact it can be a python web-service written in flask) that helps Chainlink nodes do extra tasks or get data from sources that they can't handle by default. External adapters are like helpers that extend what Chainlink nodes can do. They allow the node to connect to more complex systems, access different types of data, or perform custom calculations.
 - When a smart contract needs some data or computation that a Chainlink node can't provide directly, it can ask for the help of an external adapter. The node sends the request to the external adapter, which does the job and sends the result back to the node. The node then provides the result to the smart contract.

So in fact here we need to:
1) Choose a data source. We need to find a reliable data source that provides TWAP or VWAP data. Many popular cryptocurrency exchanges and data providers offer API access to historical or real-time TWAP and VWAP values. 
2) Create an external adapter. The adapter should be able to receive requests from a Chainlink node, query the API for TWAP or VWAP data, and return the results in a format compatible with Chainlink nodes.  

Chainlink nodes send requests to external adapters using the POST method by default, so overall we just need to create small Flask web app with two `get_twap` and `get_vwap` POST methods.

**Comment by tamriq** [comment]
FYI @gpsaggese

**Comment by gpsaggese** [comment]
Specs are very clear and this looks like a fun project!

1) Let's build the simplest skateboard possible (e.g., get the data from chainlink and accumulate the TWAP and serve it).

2) FYI we could use our own interface to Binance to use the prices (e.g., @dremdem and @jsmerix) but in general we want to get DaoSwap as independent from our stuff as possible, so we would just copy-paste code rather than relying on our Airflow infra.

3) One theoretical thing that it's not clear to me is how the external adapter is trusted. I would imagine that there should be several copies of the service with open-source code to "guarantee" that there is no "cheating" off-chain.
In any case, I'll read the white paper and I'm sure there is an answer to this.

**Comment by tamriq** [comment]
3. Yes in my opinion the code for external provider should be open-source otherwise it's suspicious
