### ISSUE TITLE
Failing docker container on ulimit

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#663]
For some reason this PR https://github.com/sorrentum/sorrentum/pull/662 is failing in Sorrentum
with the container not even start on GH, while it works for me locally
```
 73 run_fast_tests  Run fast tests  2024-02-21T00:00:42.8353290Z # Configure env
 74 run_fast_tests  Run fast tests  2024-02-21T00:00:42.8358053Z # Set up Docker-in-docker
 75 run_fast_tests  Run fast tests  2024-02-21T00:00:42.8783205Z { "storage-driver": "vfs" }
 76 run_fast_tests  Run fast tests  2024-02-21T00:00:42.9584377Z /etc/init.d/docker: 62: ulimit: error setting limit (Invalid argument)
 77 run_fast_tests  Run fast tests  2024-02-21T00:00:43.1166534Z ^[[31mERROR^[[0m: 2
 78 run_fast_tests  Run fast tests  2024-02-21T00:00:43.2582521Z ##[error]Process completed with exit code 2.
```

Do you know what's the problem?

It might be something silly, like the container and the Docker scripts not being in sync...

FYI @samarth9008

**Comment by dremdem** [comment]
The issue comes with the new version of the docker CLI: 
https://github.com/docker/cli/issues/4807
In short: the setting `ulimit` parameter break some limitation inside the docker. 
The bandaid is comment out this line `ulimit...` inside the `/etc/init.d/docker`.


I saw Samarth fixed it already in the sorrentum repo:
https://github.com/sorrentum/sorrentum/pull/661

Is the issue still persistent?

**Comment by samarth9008** [comment]
Not needed so closing it
